databases:
  - name: lumni
    databaseName: lumni
    user: root

 services:
 - type: pserv
   name: pgbouncer
   env: docker
   plan: starter plus
   repo: https://github.com/render-oss/docker-pgbouncer
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: lumni
       property: postgres://root:IVHcu7gXyibiNq9B2cnpzERNLmpmewLg@dpg-cd02q44gqg4ftbmkiqpg-a/lumni
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50